apiVersion: v1
kind: Pod
metadata:
  name: test-k-pod
  namespace: default
  labels:
    app: test-k-pod
  annotations:
    kubectl.kubernetes.io/default-container: test-k-pod
spec:
  containers:
  - name: test-k-pod
    image: jayesh1410/node-docker-app
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true
  volumes:
  - name: localtime
    hostPath:
      path: /usr/share/zoneinfo/Asia/Taipei
      type: File
  restartPolicy: Always

